Update vault haproxy template
stackhpc/stackhpc-kayobe-config pull request #1047
Opened 2024-04-23 17:25 UTC by technowhizz

This is to stop alerts that are firing at client sites. This will also alert us if a vault is sealed and/or needs bootstrapping. 

In the future we should look at using the built in exporters as [suggested by](https://stackhpc.slack.com/archives/C01HX4N1G3X/p1710325604898319?thread_ts=1710183886.551489&cid=C01HX4N1G3X) @dougszumski

2024-04-24 16:09 UTC, markgoddard requested changes

2024-04-24 16:09 UTC, markgoddard commented on doc/source/configuration/vault.rst
>           # 503: sealed (required for bootstrapping)
I'd like to see a successful multinode deployment with this because I remember explicitly needing 501/503 (as mentioned in these comments), and not wanting 429 to avoid hitting backup vaults.

2024-04-24 16:09 UTC, markgoddard commented on doc/source/configuration/vault.rst
>           # 503: sealed (required for bootstrapping)
These comments should be removed if we remove 501/503.

2024-04-30 19:07 UTC, technowhizz commented on doc/source/configuration/vault.rst
>           # 503: sealed (required for bootstrapping)
I think @mnasiadka [suggested](https://stackhpc.slack.com/archives/C044YBYMJBZ/p1710240011742489?thread_ts=1710239842.598759&cid=C044YBYMJBZ) that the bootstrapping is done via the ip of the node as opposed to using the vip. But I will try and do this in a multinode and update this PR

2024-06-07 09:55 UTC, markgoddard reviewed
@technowhizz I have rolled this change into #1090 and marked you as a co-author.

2024-06-28 00:30 UTC, technowhizz commented
change is in #1090

2024-06-28 00:30 UTC, closed without merging