Add command for adding member role to trusts to the docs
stackhpc/stackhpc-kayobe-config pull request #1063
Opened 2024-05-09 19:48 UTC by technowhizz

2024-05-10 08:33 UTC, MoteHue requested changes

2024-05-10 08:33 UTC, MoteHue commented on doc/source/operations/upgrading.rst
> +      );
```suggestion
      );

```
Linters are unhappy

2024-05-10 16:28 UTC, MoteHue approved these changes
LGTM

2024-05-13 12:42 UTC, markgoddard approved these changes

2024-05-13 12:42 UTC, merged