Auto convert using Grafana 11 dashboards
stackhpc/stackhpc-kayobe-config pull request #1068
Opened 2024-05-13 16:37 UTC by dougszumski

- Load dashboards into Grafana 11 preview
- View dashboard and export
- Check in changes
  - Don't allow hard coded Prometheus datasources

Needs reviewing / testing.

2024-05-14 08:34 UTC, markgoddard commented
"pluginVersion": "11.0.0-preview", looks a bit weird

2024-05-15 07:58 UTC, dougszumski commented
> "pluginVersion": "11.0.0-preview", looks a bit weird

Yeah, 11.0.0 wasn't out then, but it is now (the main advantage for this is that it provides auto-conversion). Dawud did test that they would load back into 10.x.

We can remove `-preview` now.

2024-05-20 10:40 UTC, dougszumski commented
Please can you test this @technowhizz ?

I have switched to the non-preview plugin version.

2024-05-24 10:47 UTC, technowhizz requested changes

2024-05-24 10:47 UTC, technowhizz commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/node_exporter_full.json
The System Processes part of this dashboard is collapsed and so it appears that they haven't been converted

2024-05-24 10:47 UTC, technowhizz commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/rabbitmq.json
The Queues, Channels and Connections sections have blank panels. The PQL is returning valid data. There seems to be an issue with the panel itself

2024-05-24 10:48 UTC, technowhizz commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/node_exporter_full.json
I fixed this in #1069 but it is still the 11.0-preview one

2024-05-31 09:24 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/rabbitmq.json
Thanks, will investigate

2024-06-10 12:36 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/node_exporter_full.json
Thanks for that- you can use `sed` to strip off the -preview. I found that worked fine. I will remove node exporter from this, in favour of your PR

2024-06-21 09:39 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/node_exporter_full.json
I've removed this in favour of your PR

2024-06-21 14:29 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/rabbitmq.json
It took me ages to find, but the trick is to remove this line:

![image](https://github.com/stackhpc/stackhpc-kayobe-config/assets/1140727/a650d8cf-995d-40e6-a822-e4b445d99fc4)

Then it works as expected!

2024-06-27 23:50 UTC, technowhizz approved these changes
LGTM

2024-06-28 09:57 UTC, merged