Build neutron-mlnx-agent kolla container
stackhpc/stackhpc-kayobe-config pull request #1093
Opened 2024-06-07 17:45 UTC by tomclark0

Enabling building of neutron-mlnx-agent kolla container for Infiniband VF support.
This container is also pulled for neutron-eswitchd, another requirement for Infiniband VF support.

2024-06-10 08:37 UTC, JohnGarbutt commented on etc/kayobe/pulp.yml
> +  - neutron-mlnx-agent
I was expecting the eswitchd image in here?

Do we need to install networking-mlnx into the nova-compute image as well, so os-vif can use the ebrctl?
https://opendev.org/x/networking-mlnx/src/commit/0a69b9715505f21fe7cca8c408c42b618d2e72d7/setup.cfg#L55

2024-06-10 08:38 UTC, JohnGarbutt commented on etc/kayobe/pulp.yml
> +  - neutron-mlnx-agent
ah, sorry, there isn't one, even better!

2024-06-10 09:07 UTC, JohnGarbutt commented
I think we should add some infiniband docs into here:
https://github.com/stackhpc/stackhpc-kayobe-config/tree/stackhpc/2023.1/doc/source/configuration

2024-06-10 12:07 UTC, markgoddard requested changes

2024-06-10 12:07 UTC, markgoddard commented on etc/kayobe/pulp.yml
> +  - neutron-mlnx-agent
This is a list of images that get synced into pulp, but doesn't control which images are built in our CI pipeline. For that you would need to set `kolla_enable_neutron_mlnx: true` in `etc/kayobe/environments/ci-builder/stackhpc-ci.yml`.

For context, this adds the regex to the kolla-build command https://opendev.org/openstack/kayobe/src/branch/master/ansible/inventory/group_vars/all/kolla#L206

2024-08-07 07:41 UTC, tomclark0 commented
Closing in favor of https://github.com/stackhpc/stackhpc-kayobe-config/pull/1211

2024-08-07 07:41 UTC, closed without merging