Bump Kolla images for CVE-2024-36039
stackhpc/stackhpc-kayobe-config pull request #1115
Opened 2024-06-26 07:34 UTC by assumptionsandg

Bump Kolla images to address [CVE-2024-36039](https://github.com/advisories/GHSA-v9hf-5j83-6xpp)

2024-06-26 08:34 UTC, markgoddard commented
Check tags job failed due to missing bifrost image.

2024-06-26 08:34 UTC, markgoddard commented
Needs a reno and more details about the CVE

2024-06-26 09:08 UTC, Alex-Welsh requested changes, later dismissed

2024-06-26 09:08 UTC, Alex-Welsh commented on etc/kayobe/kolla-image-tags.yml
> +    rocky-9: 2023.1-rocky-9-20240621T104542
The tag for `openstack` is the default, so any like this that are identical can be removed

2024-07-02 08:55 UTC, seunghun1ee submitted a review, later dismissed

2024-07-02 13:35 UTC, markgoddard requested changes
Will need to wait for #1114

2024-07-03 09:02 UTC, markgoddard commented
#1114 has merged, this can now be updated or rebased.

2024-07-03 13:17 UTC, markgoddard approved these changes, later dismissed

2024-07-03 13:25 UTC, seunghun1ee commented on etc/kayobe/kolla-image-tags.yml
> +    ubuntu-jammy: 2023.1-ubuntu-jammy-20240621T104542
Why do we have 21st June tag? Does it really includes CVE-2024-32498 fix? Did you only redo the image build and not tag generation?
Wouldn't it be better to have a tag with later date to avoid the confusion?

2024-07-03 13:42 UTC, assumptionsandg commented on etc/kayobe/kolla-image-tags.yml
> +    ubuntu-jammy: 2023.1-ubuntu-jammy-20240621T104542
It comes from [this](https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/9612397082/job/26512953962) workflow run and was built for CVE-2024-36039 and not CVE-2024-32498.

2024-07-03 13:51 UTC, seunghun1ee commented on etc/kayobe/kolla-image-tags.yml
> +    ubuntu-jammy: 2023.1-ubuntu-jammy-20240621T104542
Sorry, I realised https://github.com/stackhpc/stackhpc-kayobe-config/pull/1114 also includes fix for CVE-2024-36039 (for cinder, glance, nova) and rest of openstack are irrelevant with CVE-2024-32498.

2024-07-03 13:51 UTC, seunghun1ee submitted a review, later dismissed

2024-07-03 14:40 UTC, markgoddard commented
Rocky 9 jobs failed. It's a cryptic tempest failure, but I saw a similar issue in the upgrade jobs, and the root cause was a full disk. See #1118 for how I increased the size for upgrade jobs.

2024-07-05 11:06 UTC, markgoddard approved these changes

2024-07-05 11:06 UTC, merged