Removing angular based dashboards
stackhpc/stackhpc-kayobe-config pull request #1138
Opened 2024-07-08 14:52 UTC by GregWhiteyBialas

2024-07-09 07:53 UTC, GregWhiteyBialas commented
This is last dashboard from this task: https://stackhpc.atlassian.net/browse/INFRA-629.

2024-07-10 11:05 UTC, dougszumski requested changes
The main issue is a templating issue which prevents deployment:

```
TASK [grafana : Copying over extra configuration file] ****************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'env' is undefined. 'env' is undefined
failed: [doug-aio] (item={'path': '/home/ubuntu/src/kayobe-config/etc/kolla/config/grafana/redfish.json', 'mode': '0640', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 1000, 'gid': 1003, 'size': 92743, 'inode': 527227, 'dev': 64513, 'nlink': 1, 'atime': 1720609092.533431, 'mtime': 1720609092.1894255, 'ctime': 1720609092.533431, 'gr_name': 'kolla', 'pw_name': 'ubuntu', 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': True, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False}) => {"ansible_loop_var": "item", "changed": false, "item": {"atime": 1720609092.533431, "ctime": 1720609092.533431, "dev": 64513, "gid": 1003, "gr_name": "kolla", "inode": 527227, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0640", "mtime": 1720609092.1894255, "nlink": 1, "path": "/home/ubuntu/src/kayobe-config/etc/kolla/config/grafana/redfish.json", "pw_name": "ubuntu", "rgrp": true, "roth": false, "rusr": true, "size": 92743, "uid": 1000, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}, "msg": "AnsibleUndefinedVariable: 'env' is undefined. 'env' is undefined"}`
```

Please can you check it deploys ok and update the PR?

2024-07-10 11:05 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +          "value": "PBFA97CFB590B2093"
nit: revert

2024-07-10 11:05 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +          "text": "hpc16",
nit: Ideally we should strip these hostnames out - it should be able to handle re-populating them.

2024-07-10 11:05 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +          "expr": "count by(job) (redfish_up{env=\"hu-cloud\"})",
Need to avoid site specific `hu-cloud`

2024-07-10 12:42 UTC, GregWhiteyBialas commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +          "expr": "count by(job) (redfish_up{env=\"hu-cloud\"})",
Fixed.

2024-07-10 12:47 UTC, GregWhiteyBialas commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +          "text": "hpc16",
Fixed. It appears that Grafa, during export also keeps "selected" values in dashboards. Putting empty values makes grafana using default, which is in this case, first hostname in the list.

2024-07-10 12:48 UTC, GregWhiteyBialas commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +          "value": "PBFA97CFB590B2093"
Fixed. It appears that Grafa, during export also keeps "selected" values in dashboards. Putting empty values makes grafana using default.

2024-07-11 13:55 UTC, GregWhiteyBialas commented
@dougszumski I can't reproduce problem with deployment and missing "env" variable. I have deployed it in ci-aio env without problems. Can check again?

2024-07-12 11:05 UTC, dougszumski commented
> @dougszumski I can't reproduce problem with deployment and missing "env" variable. I have deployed it in ci-aio env without problems. Can check again?

Thanks, my bad. I had a copy lurking in the config/grafana folder which triggered the templating attempt

2024-07-12 11:10 UTC, dougszumski commented
I currently don't have an environment to test this in outside of an aio. It looks fine in the aio, and I don't see any warnings about Angular but obviously I don't have any data. We can follow up with any fixes if required - it's a good step forward, thanks @GregWhiteyBialas .

2024-07-12 11:10 UTC, dougszumski submitted a review, later dismissed

2024-07-22 08:22 UTC, dougszumski requested changes

2024-07-22 08:22 UTC, dougszumski commented on etc/kayobe/kolla/config/grafana/dashboards/openstack/redfish.json
> +<<<<<<< HEAD
Needs removing

2024-07-22 10:42 UTC, dougszumski approved these changes
Thanks @GregWhiteyBialas , all warnings resolved. I don't have access to a test env currently, but will try on sms in the near future.

Please squash the commits before merging

2024-07-22 10:43 UTC, merged

2024-07-22 10:43 UTC, dougszumski commented
> Thanks @GregWhiteyBialas , all warnings resolved. I don't have access to a test env currently, but will try on sms in the near future.
> 
> Please squash the commits before merging

Argh, auto-merge caught me out. Not to worry.