add checksum to prevent re-encryption
stackhpc/stackhpc-kayobe-config pull request #1176
Opened 2024-07-22 16:09 UTC by MaxBed4d

2024-08-30 13:57 UTC, MoteHue commented on etc/kayobe/ansible/wazuh-secrets.yml
> +      when: waz_exist_result.stat.exists
Could wrap these in a block so that ``when: waz_exist_result.stat.exists`` only needs to be specified once

2024-09-06 14:26 UTC, Alex-Welsh commented
Could you add a description to the PR saying what the problem is you're trying to solve?

2024-11-12 09:39 UTC, Alex-Welsh commented
For the record, I would approve this change but I had a hand in writing it. Can someone else approve it? Perhaps @MoteHue

2024-11-12 16:56 UTC, MoteHue requested changes
So this will successfully template and encrypt wazuh-secrets.yml the first time.
But I'm seeing the second time I run it, ansible tries and fails to interpret the file:

```
(kayobe) ubuntu@mattc-skc-aio:~/src/kayobe-config$ kayobe playbook run etc/kayobe/ansible/wazuh-secrets.yml 
[WARNING]:  * Failed to parse /home/ubuntu/venvs/kayobe/share/kayobe/ansible/inventory/hosts with yaml plugin: We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error while loading YAML.   found unknown escape character  The error appears to be in
'/home/ubuntu/src/kayobe-config/etc/kayobe/environments/ci-aio/wazuh-secrets.yml': line 10, column 20, but may be elsewhere in the file depending on the exact syntax problem.
[WARNING]:  * Failed to parse /home/ubuntu/venvs/kayobe/share/kayobe/ansible/inventory/hosts with ini plugin: We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error while loading YAML.   found unknown escape character  The error appears to be in
'/home/ubuntu/src/kayobe-config/etc/kayobe/environments/ci-aio/wazuh-secrets.yml': line 10, column 20, but may be elsewhere in the file depending on the exact syntax problem.
ERROR! Completely failed to parse inventory source /home/ubuntu/venvs/kayobe/share/kayobe/ansible/inventory/hosts
Kayobe playbook(s) etc/kayobe/ansible/wazuh-secrets.yml exited 1
```

2024-11-13 08:49 UTC, MaxBed4d commented
> So this will successfully template and encrypt wazuh-secrets.yml the first time. But I'm seeing the second time I run it, ansible tries and fails to interpret the file:
> 
> ```
> (kayobe) ubuntu@mattc-skc-aio:~/src/kayobe-config$ kayobe playbook run etc/kayobe/ansible/wazuh-secrets.yml 
> [WARNING]:  * Failed to parse /home/ubuntu/venvs/kayobe/share/kayobe/ansible/inventory/hosts with yaml plugin: We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error while loading YAML.   found unknown escape character  The error appears to be in
> '/home/ubuntu/src/kayobe-config/etc/kayobe/environments/ci-aio/wazuh-secrets.yml': line 10, column 20, but may be elsewhere in the file depending on the exact syntax problem.
> [WARNING]:  * Failed to parse /home/ubuntu/venvs/kayobe/share/kayobe/ansible/inventory/hosts with ini plugin: We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 1 (char 0)  Syntax Error while loading YAML.   found unknown escape character  The error appears to be in
> '/home/ubuntu/src/kayobe-config/etc/kayobe/environments/ci-aio/wazuh-secrets.yml': line 10, column 20, but may be elsewhere in the file depending on the exact syntax problem.
> ERROR! Completely failed to parse inventory source /home/ubuntu/venvs/kayobe/share/kayobe/ansible/inventory/hosts
> Kayobe playbook(s) etc/kayobe/ansible/wazuh-secrets.yml exited 1
> ```

@Alex-Welsh This may explain the previous formatting of the script.

2024-11-19 14:44 UTC, MaxBed4d commented
I couldn't get any errors when running any of the version of this code, and they seem to do the job, however, what has been added is a forced check to make sure that the ```wazuh_secrets.yml``` file is always encrypted, even if originally unencrypted.

2026-04-09 15:29 UTC, closed without merging