Pinning kolla, kolla-ansible and kayobe in caracal
stackhpc/stackhpc-kayobe-config pull request #1248
Opened 2024-08-23 20:37 UTC by darmach

Pinned Kolla, Kolla-Ansible and Kayobe to tags - Caracal:
 - Kolla pinned to stackhpc/18.1.0.2
 - Kolla-Ansible pinned to stackhpc/18/1/0/2
 - Kayobe pinned to stackhpc/16.1.0.1
 
 To be merged after @Alex-Welsh merges https://review.opendev.org/c/openstack/kolla-ansible/+/926618

2024-08-26 07:22 UTC, bbezak commented
shouldn't we automate the pinning process? I don't think manual updating versions is a way to go

2024-08-27 09:01 UTC, markgoddard requested changes

2024-08-27 09:01 UTC, markgoddard commented on etc/kayobe/stackhpc.yml
> -# stackhpc_kolla_ansible_source_version: "stackhpc/{{ openstack_release }}"
https://github.com/stackhpc/kolla-ansible/pull/596, available in stackhpc/18.1.0.4...

2024-08-27 09:01 UTC, markgoddard commented on etc/kayobe/stackhpc.yml
It would be better to move these versions to a separate file to allow for easier automation. `stackhpc-source-versions.yml`?

2024-08-27 09:02 UTC, markgoddard commented
> shouldn't we automate the pinning process? I don't think manual versions updating is a way to go

Agree, this is just the first step.

2024-09-09 08:36 UTC, Alex-Welsh commented
@darmach I think all the critical fixes are merged upstream now. We can merge this if you rebase & update the pins

2024-09-09 08:38 UTC, mnasiadka commented
Maybe we're a bit naive in here, who is going to pick up the burden of maintaining the pins before we get to an automated solution?

2024-09-09 08:48 UTC, Alex-Welsh commented
> Maybe we're a bit naive in here, who is going to pick up the burden of maintaining the pins before we get to an automated solution?

Whoever needs the most recent changes probably

2024-09-09 09:28 UTC, mnasiadka commented
> > Maybe we're a bit naive in here, who is going to pick up the burden of maintaining the pins before we get to an automated solution?
> 
> Whoever needs the most recent changes probably

That's the naive part - who is going to watch for reasonable patches that come from upstream that would be beneficial to pull in? (especially security related patches)

2024-11-12 09:34 UTC, Alex-Welsh commented
We should probably close this for now, since we decided to not pin anything until we can automate it

2025-02-27 11:12 UTC, Alex-Welsh commented
Superseded by https://github.com/stackhpc/stackhpc-kayobe-config/pull/1532

2025-02-27 11:12 UTC, closed without merging