Add new RMQ versions to stackhpc_pulp_images_kolla
stackhpc/stackhpc-kayobe-config pull request #1258
Opened 2024-09-03 08:29 UTC by MoteHue

2024-09-03 08:33 UTC, Alex-Welsh reviewed
LGTM but should probably wait for a responsible adult to review too

2024-09-04 01:44 UTC, seunghun1ee commented
LGTM but I agree with Alex

2024-09-04 12:57 UTC, markgoddard requested changes, later dismissed

2024-09-04 12:57 UTC, markgoddard commented on etc/kayobe/pulp.yml
> +  - rabbitmq-3-13
I think this is correct, but checking has exposed a different issue:
```
mark@lasagne:~$ skopeo list-tags docker://ark.stackhpc.com/stackhpc-dev/rabbitmq-3-12
{
    "Repository": "ark.stackhpc.com/stackhpc-dev/rabbitmq-3-12",
    "Tags": [
        "2023.1-rocky-9-20240823T101942",
        "2023.1-ubuntu-jammy-20240823T101942"
    ]
}
mark@lasagne:~$ skopeo list-tags docker://ark.stackhpc.com/stackhpc-dev/rabbitmq-3-13
{
    "Repository": "ark.stackhpc.com/stackhpc-dev/rabbitmq-3-13",
    "Tags": [
        "2023.1-rocky-9-20240823T101942",
        "2023.1-ubuntu-jammy-20240823T101942"
    ]
}
mark@lasagne:~$ skopeo list-tags docker://ark.stackhpc.com/stackhpc/rabbitmq-3-13
FATA[0001] Error listing repository tags: fetching tags list: invalid status code from registry 404 (Not Found) 
mark@lasagne:~$ skopeo list-tags docker://ark.stackhpc.com/stackhpc/rabbitmq-3-12
FATA[0003] Error listing repository tags: fetching tags list: invalid status code from registry 404 (Not Found) 
```
I think this is because we need both this change and a similar change to this one, but in stackhpc-release-train's `kolla_container_images`.

2024-09-04 12:57 UTC, markgoddard commented on etc/kayobe/pulp.yml
> +  - rabbitmq-3-13
At that point you might need to promote the above images manually.

2024-09-05 14:28 UTC, MoteHue commented on etc/kayobe/pulp.yml
> +  - rabbitmq-3-13
I've proposed that change here:
https://github.com/stackhpc/stackhpc-release-train/pull/328

2024-09-05 15:16 UTC, bbezak approved these changes

2024-09-05 15:16 UTC, Alex-Welsh commented on etc/kayobe/pulp.yml
> +  - rabbitmq-3-13
Done

2024-09-05 15:16 UTC, MoteHue commented on etc/kayobe/pulp.yml
> +  - rabbitmq-3-13
Merged and promoted

2024-09-05 15:18 UTC, merged