Amending paths to match Ark
stackhpc/stackhpc-kayobe-config pull request #1382
Opened 2024-11-22 09:50 UTC by jjo93sa

- Treasuredata needs to reference v5 not v4 and the Ark path includes `lts`
- RabbitMQ path should reference `noarch` rather than `x86_64`

Found during the upgrade of Graphcore CL0 from Antelope to Caracal

2024-11-22 09:53 UTC, m-bull requested changes
Thanks @jjo93sa - just a couple of downstream changes from your config that could do with a clean up please.

2024-11-22 09:53 UTC, m-bull commented on etc/kayobe/pulp.yml
> +stackhpc_release_pulp_username: graphcore
Please could you remove this change?

2024-11-22 09:53 UTC, m-bull commented on etc/kayobe/pulp.yml
> +stackhpc_release_pulp_password: "{{ secrets_stackhpc_release_pulp_password }}"
and this one

2024-11-22 09:53 UTC, m-bull commented on etc/kayobe/pulp.yml
> +stackhpc_pulp_sync_for_local_container_build: true
and this one!

2024-11-22 09:57 UTC, jjo93sa commented on etc/kayobe/pulp.yml
> +stackhpc_release_pulp_username: graphcore
Done

2024-11-22 09:57 UTC, jjo93sa commented on etc/kayobe/pulp.yml
> +stackhpc_release_pulp_password: "{{ secrets_stackhpc_release_pulp_password }}"
And this one is done too

2024-11-22 09:57 UTC, jjo93sa commented on etc/kayobe/pulp.yml
> +stackhpc_pulp_sync_for_local_container_build: true
As is this one

2024-11-22 10:00 UTC, m-bull approved these changes

2024-12-12 16:21 UTC, MoteHue commented
Unfortunately it looks like our CI can't handle external contributors, we don't get very many of these. I've pushed to a new branch under my auth here: https://github.com/stackhpc/stackhpc-kayobe-config/pull/1426

Thanks for the fix @jjo93sa! We'll look into fixing external contributions in the future

2024-12-12 16:21 UTC, closed without merging