Update for latest RL 9.5 image tags
stackhpc/stackhpc-kayobe-config pull request #1413
Opened 2024-12-09 11:51 UTC by MaxBed4d

2024-12-09 12:05 UTC, Alex-Welsh requested changes
Can you tell us what testing you've done for these images? Minor version bumps like this are one of the things we need to be most careful with.

Missing some changes around [here](https://github.com/stackhpc/stackhpc-kayobe-config/blame/stackhpc/2024.1/etc/kayobe/pulp.yml#L215)

Needs a release note

See this PR for a good example of how we've done all this before: https://github.com/stackhpc/stackhpc-kayobe-config/pull/1164/files

2024-12-09 12:05 UTC, Alex-Welsh commented on etc/kayobe/kolla-image-tags.yml
> +    rocky-9: 2024.1-rocky-9-20241126T102910
If you've rebuilt all the images, you can delete all the other rocky-9 tags in this file

2024-12-12 10:21 UTC, Alex-Welsh commented
@MaxBed4d I don't want this PR to get forgotten and stale, we should try to finish it off as soon as possible. If you need a hand getting it over the line let me know

2024-12-12 10:36 UTC, seunghun1ee commented
I agree. We have new Caracal deployment ongoing that is planning to use RL 9.5 as host image. This support will be needed very soon.

2025-01-02 14:38 UTC, cityofships commented
Has this not been superseded by #1430?

2025-01-02 14:39 UTC, closed without merging