Use Caracal Magnum
stackhpc/stackhpc-kayobe-config pull request #1432
Opened 2024-12-20 13:55 UTC by cityofships

To be merged after #1430

2024-12-20 15:27 UTC, cityofships commented
Perhaps should be merged without waiting for CI - Magnum's not tested.

2024-12-23 11:39 UTC, mnasiadka submitted a review, later dismissed

2025-01-03 11:40 UTC, mnasiadka requested changes

2025-01-03 11:40 UTC, mnasiadka commented on etc/kayobe/kolla.yml
> +    - magnum-capi-helm
We've lost version pinning here

2025-01-03 11:40 UTC, mnasiadka commented on etc/kayobe/kolla.yml
>      RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | head -n -1 | bash
This is not required anymore - see https://review.opendev.org/c/openstack/kolla/+/937838

2025-01-03 11:40 UTC, mnasiadka commented on releasenotes/notes/update-magnum-containers-8814b1425ec45fc0.yaml
> +    Updates Magnum to a proper Caracal release version following critical bug
Current version will also bump magnum-capi-helm to latest pypi version i.e. 1.2.0

2025-01-07 13:27 UTC, sd109 commented
FWIW unpinning the driver version here feels wrong to me. Since we're not 100% in control of upstream driver releases, we could in theory be broken if other upstream Magnum core reviewers start becoming more active in the driver lifecycle and publishing releases themselves. Maybe we could pin to minor version so that we still get automatic patch releases when rebuilding containers?

2025-01-24 10:57 UTC, cityofships commented
> FWIW unpinning the driver version here feels wrong to me. Since we're not 100% in control of upstream driver releases, we could in theory be broken if other upstream Magnum core reviewers start becoming more active in the driver lifecycle and publishing releases themselves. Maybe we could pin to minor version so that we still get automatic patch releases when rebuilding containers?

The goal of this PR was to remove Antelope's pin on Magnum itself and it scope crept a little bit. Whether to unpin the driver should be a separate discussion, so I'm just bumping its version here.

2025-01-24 16:29 UTC, mnasiadka approved these changes

2025-01-24 16:30 UTC, merged