Configure controllers
stackhpc/stackhpc-kayobe-config pull request #157
Opened 2022-09-12 14:08 UTC by jackhodgkiss

2022-09-12 14:46 UTC, markgoddard requested changes

2022-09-12 14:46 UTC, markgoddard commented on etc/kayobe/ansible/requirements.yml
> +    src: https://github.com/stackhpc/ansible-role-vxlan.git
It would be nice to get this onto Ansible galaxy at some point.

2022-09-12 14:46 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/inventory/hosts
> +# A single all-in-one controller/compute host.
This should be autogenerated - we shouldn't commit it

2022-09-12 14:46 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/kolla/passwords.yml
> +---
Shouldn't commit passwords to this branch

2022-09-12 14:46 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/tf-networks.yml
> +---
Also autogenerated

2022-09-13 10:38 UTC, jackhodgkiss commented on etc/kayobe/ansible/requirements.yml
> +    src: https://github.com/stackhpc/ansible-role-vxlan.git
Opened a PR to add `publish-role` to https://github.com/stackhpc/ansible-role-vxlan via source repositories. 

https://github.com/stackhpc/stackhpc-release-train/pull/125

2022-09-13 11:01 UTC, markgoddard approved these changes

2022-09-13 11:21 UTC, merged