Xena multinode
stackhpc/stackhpc-kayobe-config pull request #182
Opened 2022-10-05 13:26 UTC by grzegorzkoper

2022-10-05 14:39 UTC, markgoddard requested changes

2022-10-05 14:39 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/kolla/globals.yml
> +openstack_service_rpc_workers: "1"
hmm, we should probably drop these when the compute node is bare metal.

2022-10-05 14:39 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/stackhpc-ci.yml
> +stackhpc_repo_docker_ce_ubuntu_version: "{{ stackhpc_pulp_repo_docker_ce_ubuntu_version }}"
This should be updated to match the same file in the ci-builder environment

2022-10-05 14:40 UTC, markgoddard commented
You'll need to cherry-pick this one across: https://github.com/stackhpc/stackhpc-kayobe-config/pull/183

2022-10-12 09:00 UTC, markgoddard commented on etc/kayobe/storage.yml
> +  - "{{ stackhpc_lvm_group_rootvg }}"
This should be in the environment directory, not the base config

2022-10-12 09:01 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/README.md
> +# Multinode Test Environment
Jack has since made some changes to these docs.

2022-10-12 09:12 UTC, grzegorzkoper commented on etc/kayobe/environments/ci-multinode/README.md
> +# Multinode Test Environment
Should we just merge the multimode-steps branch after we're done ? There will be changes there still. Naming convention will change in terraform.

2022-10-12 10:25 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/storage.yml
> +---
Please remove the comments, similar to compute.yml and controllers.yml

2022-10-12 10:25 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/README.md
> +# Multinode Test Environment
Yes, that branch should be merged.

2022-10-13 10:00 UTC, markgoddard approved these changes, later dismissed
Nice work @jackhodgkiss @grzegorzkoper

2022-10-13 10:02 UTC, merged