Switch to using absolute limit for low memory alert
stackhpc/stackhpc-kayobe-config pull request #247
Opened 2022-11-24 15:34 UTC by jovial

Nodes with alot of ram can end up triggering this low memory alert even when they have a significant amount of free memory e.g for a node with 512GiB ram, when we hit the current alert (which is con figured to be 80%) we still have 102.5GiB free.

2022-11-24 16:26 UTC, priteau requested changes
In commit message: alot -> a lot

Add new line at end of globals.yml

2022-11-24 16:26 UTC, priteau commented on etc/kayobe/kolla/globals.yml
> +# amount of free memory is lower that this value an alert will
that -> than

2022-11-24 16:27 UTC, priteau requested changes

2022-11-24 16:27 UTC, priteau commented on etc/kayobe/kolla/globals.yml
> +alertmanager_low_memory_threshold_gb: 5
Should we use gib instead of gb?

2022-11-25 09:40 UTC, jovial commented on etc/kayobe/kolla/config/prometheus/system.rules
> +    expr: (node_memory_MemAvailable_bytes / 1024^3) < {{ alertmanager_low_memory_threshold_gb }}
```suggestion
    expr: (node_memory_MemAvailable_bytes / 1024^3) < {{ alertmanager_low_memory_threshold_gib }}
```

2022-11-25 09:40 UTC, jovial commented on etc/kayobe/kolla/globals.yml
> +# amount of free memory is lower that this value an alert will
```suggestion
# amount of free memory is lower than this value an alert will
```

2022-11-25 09:40 UTC, jovial commented on etc/kayobe/kolla/globals.yml
> +alertmanager_low_memory_threshold_gb: 5
```suggestion
alertmanager_low_memory_threshold_gib: 5
```

2022-11-25 09:40 UTC, jovial commented on etc/kayobe/kolla/globals.yml
> +#############################################################################
```suggestion
#############################################################################

```

2022-11-25 09:41 UTC, jovial commented on etc/kayobe/kolla/globals.yml
> +# amount of free memory is lower that this value an alert will
Done, thanks.

2022-11-25 09:42 UTC, jovial commented on etc/kayobe/kolla/globals.yml
> +alertmanager_low_memory_threshold_gb: 5
Good idea, I've changed it.

2022-11-25 10:21 UTC, dougszumski approved these changes
Good change. Unrelated CI fail. Would be helpful to squash on merge.

2022-11-28 09:30 UTC, markgoddard approved these changes

2022-11-28 09:30 UTC, merged

2022-11-29 13:34 UTC, bbezak commented
we're using RAW statement in the beginning of the file, therefore this change is not enough

2022-11-29 13:39 UTC, bbezak commented
we could probably add endraw/raw between this new variable @jovial