Include Rocky minor version in repo URL
stackhpc/stackhpc-kayobe-config pull request #283
Opened 2022-12-06 09:31 UTC by m-bull

2022-12-06 09:31 UTC, m-bull commented
Some discussion here: https://github.com/stackhpc/stackhpc-kayobe-config/pull/277#discussion_r1039538771

2022-12-06 14:20 UTC, markgoddard requested changes

2022-12-06 14:20 UTC, markgoddard commented on etc/kayobe/stackhpc.yml
> +stackhpc_repo_rocky_baseos_url: "{{ stackhpc_repo_mirror_url }}/pulp/content/rocky/8.{{ stackhpc_pulp_repo_rocky_8_minor_version }}/BaseOS/x86_64/os/{{ stackhpc_repo_rocky_baseos_version }}/"
Based on `base_path` in etc/kayobe/pulp.yml, I think just 8 is correct. This was done to avoid needing to update repo files for minor version bumps.

2022-12-06 14:24 UTC, markgoddard commented on etc/kayobe/stackhpc.yml
> +stackhpc_repo_rocky_baseos_url: "{{ stackhpc_repo_mirror_url }}/pulp/content/rocky/8.{{ stackhpc_pulp_repo_rocky_8_minor_version }}/BaseOS/x86_64/os/{{ stackhpc_repo_rocky_baseos_version }}/"
I suppose the problem is that test pulp on SMS lab does not follow this pattern - it has a different base_path for each minor version.

We could override the rocky URL variables in etc/kayobe/environments/ci-aio/stackhpc-ci.yml

2022-12-06 16:10 UTC, m-bull commented on etc/kayobe/stackhpc.yml
> +stackhpc_repo_rocky_baseos_url: "{{ stackhpc_repo_mirror_url }}/pulp/content/rocky/8.{{ stackhpc_pulp_repo_rocky_8_minor_version }}/BaseOS/x86_64/os/{{ stackhpc_repo_rocky_baseos_version }}/"
Yeah - all good points, I got very confused!

Overrode Rocky URL vars in `stackhpc-ci.yml` as suggested.

2022-12-07 09:19 UTC, markgoddard approved these changes

2022-12-07 09:19 UTC, merged