Bump grafana repository snapshot version
stackhpc/stackhpc-kayobe-config pull request #37
Opened 2022-02-10 15:37 UTC by jovial

Bump the grafana version to 8.3.3 from 8.3.1 to include the fix for the following issue:

https://github.com/grafana/grafana/issues/42605

We seem to be using a variable for the min-step in a number of our dashboards.

2022-02-10 15:41 UTC, markgoddard commented
LGTM, I'll build an image with this repo.

2022-02-10 15:43 UTC, jovial commented
> LGTM, I'll build an image with this repo.

Thank you.

2022-02-10 16:04 UTC, markgoddard commented
Will be tagged as `wallaby-20220119T122428`

2022-02-10 16:09 UTC, jovial commented
> wallaby-20220119T122428

Should I update this PR with that version? Or do you want a separate PR for that change?

2022-02-10 16:11 UTC, markgoddard commented
> > wallaby-20220119T122428
> 
> Should I update this PR with that version? Or do you want a separate PR for that change?

Please update this PR.

2022-02-10 16:12 UTC, markgoddard commented
@jovial I'll let you promote the container image tag: https://github.com/stackhpc/stackhpc-release-train/actions/workflows/container-promote.yml

It will be backed up behind a sync job for a while. We could cancel that if you need this sooner.

2022-02-10 16:23 UTC, jovial commented
Suggested edit:
```diff
diff --git a/etc/kayobe/kolla/globals.yml b/etc/kayobe/kolla/globals.yml
--- etc/kayobe/kolla/globals.yml
+++ etc/kayobe/kolla/globals.yml
@@ -2,8 +2,9 @@
 docker_yum_baseurl: "{{ stackhpc_repo_docker_url }}"
 docker_yum_gpgkey: "https://download.docker.com/linux/{% raw %}{{ ansible_facts.distribution | lower }}{% endraw %}/gpg"
 
 cloudkitty_tag: wallaby-20220119T122428
+grafana_tag: wallaby-20220119T122428
 horizon_tag: wallaby-20220119T122428
 manila_tag: wallaby-20211210T140839
 neutron_tag: wallaby-20220104T102739
 neutron_sriov_agent_tag: wallaby-20220110T113538

```

2022-02-10 16:43 UTC, markgoddard requested changes

2022-02-10 16:43 UTC, markgoddard commented on etc/kayobe/kolla/globals.yml
> +grafana_tag: wallaby-20220119T122428
Wrong tag!

2022-02-10 16:45 UTC, markgoddard commented on etc/kayobe/kolla/globals.yml
> +grafana_tag: wallaby-20220119T122428
Sorry, my mistake. I grabbed the tag too early. It should be `wallaby-20220210T160332`.

2022-02-10 17:47 UTC, markgoddard approved these changes

2022-02-11 10:20 UTC, merged

2022-02-11 10:20 UTC, jovial commented
Tested and seems to be working. Thanks Mark.