Add new pulp repo tags
stackhpc/stackhpc-kayobe-config pull request #379
Opened 2023-02-07 15:54 UTC by MoteHue

2023-02-07 16:06 UTC, markgoddard commented
Do we need some container image tags as well?

2023-02-07 16:25 UTC, jovial commented
I've got some package versions bumps for the release notes:

```
[will@juno stackhpc-release-train-package-versions]$ jq '. | map(select(.name=="kernel")) | sort_by(.version, .release) | last' centos/8-stream/BaseOS/x86_64/os/*/packages.json
{
  "arch": "x86_64",
  "name": "kernel",
  "release": "408.el8",
  "version": "4.18.0"
}
{
  "arch": "x86_64",
  "name": "kernel",
  "release": "448.el8",
  "version": "4.18.0"
}
```

```
[will@juno stackhpc-release-train-package-versions]$ jq '. | map(select(.name | test( "^ovn[^-]*$"))) | sort_by(.version, .release) | last' centos/8-stream/nfv/x86_64/openvswitch-2/*/packages.json
{
  "arch": "x86_64",
  "name": "ovn22.06",
  "release": "24.el8s",
  "version": "22.06.0"
}
{
  "arch": "x86_64",
  "name": "ovn22.09",
  "release": "11.el8s",
  "version": "22.09.0"
}

```

```
[will@juno stackhpc-release-train-package-versions]$ jq '. | map(select(.name | test( "^openvswitch[^-]*$"))) | sort_by(.version, .release) | last' centos/8-stream/nfv/x86_64/openvswitch-2/*/packages.json
{
  "arch": "x86_64",
  "name": "openvswitch2.17",
  "release": "31.el8s",
  "version": "2.17.0"
}
{
  "arch": "x86_64",
  "name": "openvswitch2.17",
  "release": "71.el8s",
  "version": "2.17.0"
}
```

libvirt remains the same

2023-02-07 16:27 UTC, jovial commented
> Do we need some container image tags as well?

They are building here: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/4115798154

2023-02-07 16:56 UTC, markgoddard commented
> > Do we need some container image tags as well?
> 
> They are building here: https://github.com/stackhpc/stackhpc-kayobe-config/actions/runs/4115798154

Ok. Bear in mind bifrost is built separately, and will end up with a different tag.

2023-02-08 14:21 UTC, jovial commented
Looks good. I will merge into `https://github.com/stackhpc/stackhpc-kayobe-config/tree/refresh/multinode-load-balancers`. Which is the wallaby/branch merged in multinode-load-balancers (wallaby multinode environment).

2023-02-10 17:34 UTC, jovial commented
Lets add a release note saying packages have being refreshed and summarise versions of these packages:

-  kernel version
- libvirt version
- ovs version
- ovn version

2023-02-13 09:40 UTC, markgoddard commented
> Lets add a release note saying packages have being refreshed and summarise versions of these packages:
> 
> * kernel version
> * libvirt version
> * ovs version
> * ovn version

Yes, let's :)

2023-02-13 10:19 UTC, MoteHue commented
> > Lets add a release note saying packages have being refreshed and summarise versions of these packages:
> > 
> > * kernel version
> > * libvirt version
> > * ovs version
> > * ovn version
> 
> Yes, let's :)

I've added the latest releases and versions from [this repo](https://github.com/stackhpc/stackhpc-release-train-package-versions). I don't know why there's so many different versions of each listed, so would appreciate if this can be double checked :)

2023-02-13 10:32 UTC, markgoddard requested changes

2023-02-13 10:32 UTC, markgoddard commented on releasenotes/notes/release-train-02-2023-package-refresh-9de8049f8cb08a5e.yaml
> +    The package repositories have been refreshed. Key packages to note are:
```suggestion
    Package repositories and container images for CentOS Stream based deployments have been updated.
    Key packages to note are:

```

2023-02-13 10:32 UTC, markgoddard commented on releasenotes/notes/release-train-02-2023-package-refresh-9de8049f8cb08a5e.yaml
> +    The package repositories have been refreshed. Key packages to note are:
Note the empty line, required by RST before lists

2023-02-13 11:42 UTC, markgoddard approved these changes

2023-02-13 13:09 UTC, merged

2023-02-13 14:36 UTC, priteau reviewed
This was merged already but I think there are errors in the release note.

2023-02-13 14:36 UTC, priteau commented on releasenotes/notes/release-train-02-2023-package-refresh-9de8049f8cb08a5e.yaml
> +      * release: 408.el8
Is the kernel version correct? 408 was released in July and already present in the last package sync. I would have expected 448: https://koji.mbox.centos.org/koji/buildinfo?buildID=23410

2023-02-13 14:36 UTC, priteau commented on releasenotes/notes/release-train-02-2023-package-refresh-9de8049f8cb08a5e.yaml
> +      * version: 7.6.0
The nova-libvirt container images we built recently were all using Libvirt 8.0.0. Did you change the configuration to get Libvirt from somewhere else?