Update Openstack Dashboard
stackhpc/stackhpc-kayobe-config pull request #406
Opened 2023-02-22 13:32 UTC by technowhizz

Updates the Openstack dashboard to show http 300 status codes as green as this is the expected return code from some services.

2023-02-22 16:21 UTC, markgoddard requested changes
Please propose to stackhpc/xena instead

2023-02-22 18:44 UTC, technowhizz commented
@markgoddard proposed against xena

2023-02-23 08:52 UTC, markgoddard commented on releasenotes/notes/openstack-dash-ff7bf179e37c8e4b.yaml
> +    Changes the openstack dashboard to show http status 300 as green instead of
```suggestion
    Changes the Grafana OpenStack dashboard to show HTTP status 300 as green instead of
```

2023-02-23 09:14 UTC, technowhizz commented on releasenotes/notes/openstack-dash-ff7bf179e37c8e4b.yaml
> +    Changes the openstack dashboard to show http status 300 as green instead of
Applied

2023-02-23 09:26 UTC, markgoddard approved these changes

2023-02-23 09:26 UTC, merged