Multinode Magnum missing changes
stackhpc/stackhpc-kayobe-config pull request #462
Opened 2023-03-30 12:30 UTC by darmach

Added missing routing from controllers back to seed node. Enabled Magnum, added config.

2023-03-30 15:01 UTC, markgoddard requested changes

2023-03-30 15:01 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/inventory/group_vars/controllers/network-interfaces
> +public_routes:
So this is to allow magnum to access floating IPs to communicate with k8s clusters?

2023-03-30 15:01 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/inventory/group_vars/controllers/network-interfaces
> +    gateway: "{{ public_allocation_pool_start }}"
```suggestion
    gateway: "{{ public_net_name | net_ip('seed') }}"
```

2023-04-03 10:59 UTC, darmach commented on etc/kayobe/environments/ci-multinode/inventory/group_vars/controllers/network-interfaces
> +public_routes:
Without this heat container agent was failing to grab token off keystone endpoint running on 192.168.39.2 - public network 192.168.39.0/24. It was reaching keystone fine, but replies weren't going back to external network where master was (source).

2023-04-05 08:15 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/inventory/group_vars/controllers/network-interfaces
> +    gateway: "{{ public_allocation_pool_start }}"
How about this? Trying to remove the assumption that the seed has the first IP in the pool

2023-04-05 21:02 UTC, darmach commented on etc/kayobe/environments/ci-multinode/inventory/group_vars/controllers/network-interfaces
> +    gateway: "{{ public_allocation_pool_start }}"
Yes, it absolutely makes sense and is a more elegant choice :)

2023-04-06 07:50 UTC, markgoddard approved these changes

2023-04-06 07:50 UTC, merged