Overcloud database backup S3 upload
stackhpc/stackhpc-kayobe-config pull request #560
Opened 2023-07-13 12:26 UTC by darmach

Added playbook uploading overcloud MariaDB backups to S3 compatible storage. Can be linked as overcloud database backup post hook.

2023-10-12 15:00 UTC, Alex-Welsh commented
This seems useful. Was it ever tested/working?

2023-10-12 15:19 UTC, MoteHue commented
> Was it ever tested/working?

This is actively in use at (at least one) clients for nightly backups :)

2023-10-12 15:24 UTC, darmach commented
> This seems useful. Was it ever tested/working?
Yes, I developed this for AZ originally, and works so far :)

2023-10-12 15:32 UTC, Alex-Welsh commented
> This is actively in use at (at least one) clients for nightly backups :)

> Yes, I developed this for AZ originally, and works so far :)

Shall we try to get it merged?

2024-02-20 14:23 UTC, markgoddard submitted a review, later dismissed

2024-02-20 14:23 UTC, markgoddard commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +    # This playbook uploads MariaDB backups to an AWS S3 object store.
nit: please remove unnecessary indentation

2024-02-20 14:23 UTC, markgoddard commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +        kayobe_venv: "/opt/kayobe/venvs/kayobe"
```suggestion
        kayobe_venv: "{{ virtualenv_path }}/kayobe"
```

2024-02-20 14:23 UTC, markgoddard commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +            bucket: "{{ s3_mariadb_mysql_backup_bucket }}"
```suggestion
            s3_url: "{{ s3_mariadb_backup_url }}"
            access_key: "{{ secrets_s3_mariadb_backup_access_key }}"
            secret_key: "{{ secrets_s3_mariadb_backup_secret_key }}"
            bucket: "{{ s3_mariadb_backup_bucket }}"
```

2024-02-20 14:23 UTC, markgoddard commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +            validate_certs: False
:(

2024-02-20 14:23 UTC, markgoddard commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +---
This could use some documentation, probably in somewhere like `doc/source/operations/database-backups.rst`

2025-12-17 15:35 UTC, MoteHue commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +    # This playbook uploads MariaDB backups to an AWS S3 object store.
done

2025-12-17 15:52 UTC, MoteHue commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +            validate_certs: False
:(

2025-12-17 15:52 UTC, MoteHue commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +---
Done

2025-12-17 16:51 UTC, Alex-Welsh requested changes

2025-12-17 16:51 UTC, Alex-Welsh commented on doc/source/operations/database-backups.rst
> +   ln -s ../../../ansible/upload-database-backup-s3.yml $KAYOBE_CONFIG_PATH/hooks/overcloud-database-backup/post.d/10-upload-database-backup-s3.yml
```suggestion
   ln -s ../../../ansible/tools/upload-database-backup-s3.yml $KAYOBE_CONFIG_PATH/hooks/overcloud-database-backup/post.d/10-upload-database-backup-s3.yml
```

2025-12-18 09:27 UTC, Alex-Welsh commented on etc/kayobe/ansible/upload-database-backup-s3.yml
> +            validate_certs: False
:(

2025-12-18 09:27 UTC, Alex-Welsh approved these changes

2025-12-18 09:28 UTC, merged