CI: seed container image builds, trigger image sync to test pulp
stackhpc/stackhpc-kayobe-config pull request #60
Opened 2022-04-29 13:25 UTC by markgoddard

2022-05-31 15:27 UTC, priteau requested changes

2022-05-31 15:27 UTC, priteau commented on .github/workflows/container-image-build.yml
> +        if: github.events.input.overcloud
I think all occurrences of `github.events` should be `github.event`.

However I haven't yet verified that the change for `input.regexes` above fixed it.

2022-05-31 15:39 UTC, markgoddard commented on .github/workflows/container-image-build.yml
> +        if: github.events.input.overcloud
Good catch

2022-06-01 14:24 UTC, priteau commented on .github/workflows/container-image-build.yml
> +        if: github.events.input.overcloud
And it should actually be `github.event.inputs` rather than `github.event.input` 😓

2022-06-01 14:31 UTC, priteau approved these changes

2022-06-01 14:32 UTC, priteau commented
@markgoddard Please check that you are happy with the additional commit I pushed.

2022-06-01 14:49 UTC, markgoddard commented on .github/workflows/container-image-build.yml
> +        if: github.events.input.overcloud
> @markgoddard Please check that you are happy with the additional commit I pushed.

Thank you for fixing up. I spotted this in another workflow :( Would be better if github failed on these invalid references.

2022-06-01 14:49 UTC, merged