Zed reno changes
stackhpc/stackhpc-kayobe-config pull request #601
Opened 2023-08-24 14:42 UTC by Alex-Welsh

This PR contains various commits that relate to upstream changes for Zed, from reading through the release notes

2023-08-24 15:41 UTC, markgoddard requested changes

2023-08-24 15:41 UTC, markgoddard commented on .github/workflows/stackhpc-container-image-build.yml
> +      # with kolla from a git repository
I think this just filters images with a label of kolla_version, so should still work

2023-08-24 15:41 UTC, markgoddard commented on doc/source/configuration/wazuh.rst
> +          mntp: “/var/lib/opensearch”
Unsure about this one. Does wazuh actually use this directory for OpenSearch? If so this should probably go in yoga too.

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/environments/aufn-ceph/kolla/globals.yml
>  es_heap_size: 1g
```suggestion
opensearch_heap_size: 1g
```

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/environments/ci-aio/kolla/globals.yml
>  es_heap_size: 1g
```suggestion
opensearch_heap_size: 1g
```

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/environments/ci-multinode/kolla/globals.yml
>  es_heap_size: 1g
```suggestion
opensearch_heap_size: 1g
```

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/compute.yml
> +# compute_swap:
Looks like these didn't make it into etc/kayobe/compute.yml in kayobe

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/ironic.yml
> +#kolla_ironic_tftp_append_params_default:
Not seeing these in Kayobe stable/zed branch

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/kolla.yml
> -#kolla_ansible_ctl_install_type:
This is still relevant, it's about the kolla-ansible python package installation

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/kolla/globals.yml
> +#image_name_prefix: "{{ os_distribution }}"
Not used - remove?

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/pulp.yml
> +  {%- set image_repo = kolla_docker_namespace ~ "/" ~ kolla_base_distro ~ "-" ~ image -%}
Also remove kolla_base_distro?

2023-08-24 15:41 UTC, markgoddard commented on etc/kayobe/pulp.yml
> +  {%- set image_repo = kolla_docker_namespace ~ "/" ~ kolla_base_distro ~ "-" ~ image -%}
ditto

2023-08-24 15:59 UTC, Alex-Welsh commented on doc/source/configuration/wazuh.rst
> +          mntp: “/var/lib/opensearch”
I think so but I'm also not sure. Might be the sort of thing we just need to shake out during multinode testing.

2023-08-24 16:17 UTC, Alex-Welsh commented on etc/kayobe/ironic.yml
> +#kolla_ironic_tftp_append_params_default:
I think these were a response to [this change](https://review.opendev.org/c/openstack/kolla-ansible/+/832134). I just assumed it had all propagated through Kayobe too.

2023-08-24 16:17 UTC, Alex-Welsh commented on etc/kayobe/ironic.yml
> +#kolla_ironic_tftp_append_params_default:
Will remove them in next patchset

2023-08-25 08:59 UTC, Alex-Welsh commented on etc/kayobe/compute.yml
> +# compute_swap:
Interesting. Do we need to change anything here or it an Upstream PR?

2023-08-25 09:23 UTC, Alex-Welsh commented on .github/workflows/stackhpc-container-image-build.yml
> +      # with kolla from a git repository
Removed

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/pulp.yml
> +  {%- set image_repo = kolla_docker_namespace ~ "/" ~ kolla_base_distro ~ "-" ~ image -%}
Done

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/pulp.yml
> +  {%- set image_repo = kolla_docker_namespace ~ "/" ~ kolla_base_distro ~ "-" ~ image -%}
Removed

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/kolla/globals.yml
> +#image_name_prefix: "{{ os_distribution }}"
Whoops. Reverted

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/environments/ci-multinode/kolla/globals.yml
>  es_heap_size: 1g
Done

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/ironic.yml
> +#kolla_ironic_tftp_append_params_default:
Done

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/environments/ci-aio/kolla/globals.yml
>  es_heap_size: 1g
Done

2023-08-25 09:24 UTC, Alex-Welsh commented on etc/kayobe/environments/aufn-ceph/kolla/globals.yml
>  es_heap_size: 1g
Done

2023-08-25 09:25 UTC, Alex-Welsh commented on etc/kayobe/kolla.yml
> -#kolla_ansible_ctl_install_type:
Whoops. Reverted

2023-08-29 09:51 UTC, markgoddard requested changes

2023-08-29 09:51 UTC, markgoddard commented on doc/source/configuration/wazuh.rst
> +          mntp: “/var/lib/opensearch”
I think let's stick with elasticsearch for now since the move to Zed isn't changing anything to do with wazuh.

2023-08-29 09:51 UTC, markgoddard commented on etc/kayobe/compute.yml
> +# compute_swap:
Nothing to change in here, but an upstream patch would be nice.

2023-08-29 10:31 UTC, Alex-Welsh commented on doc/source/configuration/wazuh.rst
> +          mntp: “/var/lib/opensearch”
Done

2023-08-29 10:33 UTC, markgoddard approved these changes

2023-08-29 12:24 UTC, Alex-Welsh commented
Going to need you to force merge this unfortunately @markgoddard. CI's still blocking

2023-08-29 13:22 UTC, merged