AIO script improvements
stackhpc/stackhpc-kayobe-config pull request #602
Opened 2023-08-24 15:31 UTC by assumptionsandg

Added --lvm option to allow the AIO automatic deployment script to run on LVM images. Also changes to python virtual environment dependencies and creation for Rocky9 and Ubuntu Jammy.

2023-08-24 15:36 UTC, Alex-Welsh commented
From in person conversation - It would probably make more sense to invert this and make the LVM specific steps default, then make a `--non-lvm` flag that skips them if required

2023-08-24 15:41 UTC, assumptionsandg commented
Added --non-lvm option.

2023-08-25 09:57 UTC, MoteHue requested changes

2023-08-25 09:57 UTC, MoteHue commented on doc/source/contributor/environments/ci-aio.rst
> +Adding the ``--lvm`` flag will also automatically set the LVM configuration,
```suggestion
Unless the ``--no-lvm`` flag is set, LVM configuration is automatically applied,
```

2023-08-25 15:50 UTC, Alex-Welsh submitted a review, later dismissed

2023-08-29 08:28 UTC, MoteHue approved these changes, later dismissed

2023-08-29 09:47 UTC, markgoddard commented on etc/kayobe/environments/ci-aio/automated-setup.sh
> +if [ "${1-0}" != "--non-lvm" ]; then
It would be simpler for the user to just test for the existence of any physical volumes or volume groups

2023-08-29 15:14 UTC, holliefae commented on etc/kayobe/environments/ci-aio/automated-setup.sh
> +if [ "${1-0}" != "--non-lvm" ]; then
It should automatically test now whether any volume groups exist on the image.

2023-08-29 15:19 UTC, markgoddard approved these changes

2023-08-29 15:19 UTC, merged