Add DWPD to Hardware Overview dashboard
stackhpc/stackhpc-kayobe-config pull request #621
Opened 2023-09-06 15:39 UTC by technowhizz

Adds a panel in the Hardware Overview dashboard to show DWPD (Drive writes per day) for NVMEs. This is calculated by dividing the total bytes written in the past 24 hours by the drive capacity.

2023-09-22 16:21 UTC, oneswig submitted a review, later dismissed
Good to see this

2023-09-25 10:52 UTC, dougszumski requested changes
We agreed to add the following before finishing this task:

- Short documentation section to be added explaining the limitations (only nvme supported) and how to customise the dashboard to remove the plot on systems without supported drives.
- Alert to be added, as noted in https://stackhpc.atlassian.net/browse/INFRA-395

2023-10-20 13:21 UTC, Alex-Welsh commented
@technowhizz is this still WIP? would it be better to convert to draft for now?

2023-10-20 14:05 UTC, technowhizz commented
@Alex-Welsh Nope, its waiting to be merged :)

2023-10-20 14:10 UTC, Alex-Welsh commented
> @Alex-Welsh Nope, its waiting to be merged :)

Might want to poke some potential reviewers then

2023-10-23 14:36 UTC, dougszumski submitted a review, later dismissed
Thanks @technowhizz.

2023-10-23 14:36 UTC, dougszumski commented on releasenotes/notes/dwpd-6b9fb0c8d6d3a570.yaml
> +    per day) for NVMEs. This is calculated by dividing the total bytes written
nit: You could include the alert here.

2023-10-24 10:11 UTC, technowhizz commented on releasenotes/notes/dwpd-6b9fb0c8d6d3a570.yaml
> +    per day) for NVMEs. This is calculated by dividing the total bytes written
Done

2023-10-24 10:11 UTC, technowhizz commented
@oneswig bumped up the alert durations as discussed

2023-11-13 10:56 UTC, dougszumski approved these changes

2023-11-17 11:13 UTC, merged