Correct release notes for Inception vulnerability
stackhpc/stackhpc-kayobe-config pull request #705
Opened 2023-10-11 08:33 UTC by jovial

Missing the kernel mitigation. This is required in addition to the microcode, see: https://docs.kernel.org/admin-guide/hw-vuln/srso.html.

2023-10-11 08:49 UTC, priteau requested changes

2023-10-11 08:49 UTC, priteau commented on releasenotes/notes/bump-centos8-stream-snapshots-2023-09-04-a473edfd3f3b2298.yaml
> +    (CVE-2023-20593), Downfall (CVE-2022-40982). It is recommended that you
Replace comma by "and".

2023-10-11 08:49 UTC, priteau commented on releasenotes/notes/bump-ubuntu-snapshots-2023-09-15-22ca5250d40bd5b6.yaml
> +    (CVE-2022-40982).  Zenbleed (CVE-2023-20593) was patched in the previous
Remove duplicate space.

2023-10-11 09:11 UTC, jovial commented on releasenotes/notes/bump-ubuntu-snapshots-2023-09-15-22ca5250d40bd5b6.yaml
> +    (CVE-2022-40982).  Zenbleed (CVE-2023-20593) was patched in the previous
```suggestion
    (CVE-2022-40982). Zenbleed (CVE-2023-20593) was patched in the previous
```

2023-10-11 09:11 UTC, jovial commented on releasenotes/notes/bump-centos8-stream-snapshots-2023-09-04-a473edfd3f3b2298.yaml
> +    (CVE-2023-20593), Downfall (CVE-2022-40982). It is recommended that you
```suggestion
    (CVE-2023-20593) and Downfall (CVE-2022-40982). It is recommended that you
```

2023-10-11 09:13 UTC, jovial commented on releasenotes/notes/bump-ubuntu-snapshots-2023-09-15-22ca5250d40bd5b6.yaml
> +    (CVE-2022-40982).  Zenbleed (CVE-2023-20593) was patched in the previous
done

2023-10-11 09:13 UTC, jovial commented on releasenotes/notes/bump-centos8-stream-snapshots-2023-09-04-a473edfd3f3b2298.yaml
> +    (CVE-2023-20593), Downfall (CVE-2022-40982). It is recommended that you
done

2023-10-18 08:03 UTC, priteau approved these changes

2023-10-18 08:03 UTC, merged