2023.1: zed merge
stackhpc/stackhpc-kayobe-config pull request #742
Opened 2023-11-02 12:50 UTC by markgoddard

- feat: bump bifrost tag
- feat: bump `bifrost` for `centos`
- CI: Skip aio jobs based on changed files
- Disable custom apt config for non-overcloud hosts
- Fix seed container image build
- Remove facts for purge-command-not-found.yml
- Add Opensearch to AUFN services
- CI: Add missing condition to PR workflow
- CI: Add conditions to PR workflow

2023-11-02 13:13 UTC, Alex-Welsh requested changes

2023-11-02 13:13 UTC, Alex-Welsh commented on etc/kayobe/environments/aufn-ceph/kolla/inventory/overcloud-services.j2
> +
Duplicate of existing content

2023-11-03 12:03 UTC, markgoddard commented
CI passing

2023-11-03 12:03 UTC, merged

2023-11-03 12:04 UTC, markgoddard commented
Argh fat fingers hit close instead of merge