Fixes various issues with the cis.yml playbook
stackhpc/stackhpc-kayobe-config pull request #791
Opened 2023-11-16 15:54 UTC by jovial

Apologies, turns out I should have tested the role bump more thoroughly.

2023-11-16 16:00 UTC, jovial commented on requirements.txt
> +jmespath
E.g https://github.com/ansible-lockdown/RHEL9-CIS/blob/c5a4866e1ac4bf15229d86cf6508228906313b28/tasks/pre_remediation_audit.yml#L96

2023-11-17 10:31 UTC, markgoddard requested changes

2023-11-17 10:31 UTC, markgoddard commented on doc/source/configuration/security-hardening.rst
> +  enabled. To do this you for this playbook only, you can use:
```suggestion
  enabled. To do this for this playbook only, you can use:
```

2023-11-17 10:31 UTC, markgoddard commented on etc/kayobe/ansible/requirements.yml
> +    #FIXME: https://github.com/ansible-lockdown/UBUNTU22-CIS/pull/174
```suggestion
    #FIXME: Waiting for https://github.com/ansible-lockdown/UBUNTU22-CIS/pull/174
```

2023-11-20 12:09 UTC, markgoddard approved these changes

2023-11-27 11:32 UTC, merged