Add stop-openstack-services.yml playbook
stackhpc/stackhpc-kayobe-config pull request #809
Opened 2023-11-29 16:15 UTC by Alex-Welsh

Adds a new playbook to stop openstack services across the overcloud.

I was undecided as to whether this warrants its own playbook but I've needed to use it enough times now that I think other people might want it.

One function I was considering was a variable to change the `docker stop` to a `docker restart` which we could then redirect to in the case of the `rabbitmq-reset.yml` playbook.

2023-11-29 16:30 UTC, MoteHue commented on etc/kayobe/ansible/stop-openstack-services.yml
> +    # The following services use RabbitMQ.
This comment isn't needed here

2023-11-29 16:31 UTC, MoteHue commented on releasenotes/notes/stop-services-playbook-b85b53d1a7571009.yaml
> +    stop openstack services across the overcloud.
```suggestion
    stop OpenStack services across the overcloud.
```

2023-11-29 16:33 UTC, Alex-Welsh commented on releasenotes/notes/stop-services-playbook-b85b53d1a7571009.yaml
> +    stop openstack services across the overcloud.
:angry:

2023-11-29 16:34 UTC, Alex-Welsh commented on releasenotes/notes/stop-services-playbook-b85b53d1a7571009.yaml
> +    stop openstack services across the overcloud.
Done

2023-11-29 16:34 UTC, Alex-Welsh commented on etc/kayobe/ansible/stop-openstack-services.yml
> +    # The following services use RabbitMQ.
I blame the guy I copied it from

2023-12-06 12:25 UTC, markgoddard requested changes

2023-12-06 12:25 UTC, markgoddard commented on etc/kayobe/ansible/stop-openstack-services.yml
> +    - stop_service_list:
Needs horizon & glance

2023-12-06 13:57 UTC, Alex-Welsh commented on etc/kayobe/ansible/stop-openstack-services.yml
> +    - stop_service_list:
Added

2023-12-06 13:57 UTC, Alex-Welsh commented on etc/kayobe/ansible/stop-openstack-services.yml
> +    - stop_service_list:
Plus placement

2023-12-06 14:02 UTC, mnasiadka commented
Maybe a stupid question, but what's wrong with kolla-ansible stop? ;-)

2023-12-06 14:12 UTC, markgoddard commented
> Maybe a stupid question, but what's wrong with kolla-ansible stop? ;-)

Slooooow

2023-12-06 14:24 UTC, mnasiadka commented
> > Maybe a stupid question, but what's wrong with kolla-ansible stop? ;-)
> 
> Slooooow

Correct answer, should we rework that upstream as well?

2023-12-06 14:49 UTC, markgoddard commented
> > > Maybe a stupid question, but what's wrong with kolla-ansible stop? ;-)
> > 
> > 
> > Slooooow
> 
> Correct answer, should we rework that upstream as well?

How do you propose to do it?

2023-12-06 15:23 UTC, mnasiadka commented
> > > > Maybe a stupid question, but what's wrong with kolla-ansible stop? ;-)
> > > 
> > > 
> > > Slooooow
> > 
> > 
> > Correct answer, should we rework that upstream as well?
> 
> How do you propose to do it?
Maybe a similar playbook, just for those time constrained - but we would probably need a better mechanism for being able to tell which services need stopping - maybe a playbook with a tag per play? It's going to be slower than this, but probably faster than kolla-ansible stop currently.

2023-12-06 15:25 UTC, Alex-Welsh commented
> > > > > Maybe a stupid question, but what's wrong with kolla-ansible stop? ;-)
> > > > 
> > > > 
> > > > Slooooow
> > > 
> > > 
> > > Correct answer, should we rework that upstream as well?
> > 
> > 
> > How do you propose to do it?
> > Maybe a similar playbook, just for those time constrained - but we would probably need a better mechanism for being able to tell which services need stopping - maybe a playbook with a tag per play? It's going to be slower than this, but probably faster than kolla-ansible stop currently.

Playbook with a tag per play that adds all the services to a list, then runs the stop all at once? Would be a lot faster than trying to stop them all individually.

2023-12-15 11:10 UTC, markgoddard approved these changes

2023-12-15 11:17 UTC, merged