Zed opensearch bump
stackhpc/stackhpc-kayobe-config pull request #840
Opened 2023-12-14 15:33 UTC by bbezak

(yoga have already 2.11)

2023-12-14 17:31 UTC, bbezak commented
tested in TU Wien

2023-12-14 20:50 UTC, priteau requested changes

2023-12-14 20:50 UTC, priteau commented on releasenotes/notes/2.11.1-opensearch-bump-11fc566cd57a5f39.yaml
> +    Updates Opensearch to 2.11.1
Nits:

- OpenSearch
- missing dot at the end.

2023-12-15 08:13 UTC, priteau approved these changes

2023-12-15 08:28 UTC, merged