zed: yoga merge
stackhpc/stackhpc-kayobe-config pull request #950
Opened 2024-02-20 14:43 UTC by markgoddard

- Add a note about network interfaces changes
- Bump seed Pulp to 3.43.1
- CI: Fail aio job when Terraform reaches max attempts
- Reduce Elasticsearch/OpenSearch heap size to 200m in ci-aio env
- Disable Heat in ci-aio env
- Reduce aio flavor to en1.medium
- CI: Add tags to aio VMs
- CI: Add a workflow to clean up stale instances
- CI: Use skc-ci-aio user for aio jobs
- Ubuntu Focal to Jammy migration support (#902)
- Stop warning about invalid group name characters
- CI: Clean up instances in BUILD state, list by ID
- CI: Use correct URL for upper constraints
- bumping ansible vault
- docs: Update network interface note to mention group_vars
- Enable AiO jobs to be cancelled even if they're underway.

2024-02-20 15:48 UTC, Alex-Welsh requested changes

2024-02-20 15:48 UTC, Alex-Welsh commented on etc/kayobe/ansible/ubuntu-upgrade.yml
Not required, no Zed support for Focal

2024-02-20 15:48 UTC, Alex-Welsh commented on releasenotes/notes/add-automated-ubuntu-migration-support-2d7e8a6e1a2103cc.yaml
ditto

2024-02-20 15:48 UTC, Alex-Welsh commented on tools/ubuntu-upgrade-infra-vm.sh
ditto for all these upgrade scripts

2024-02-21 08:58 UTC, markgoddard commented on etc/kayobe/ansible/ubuntu-upgrade.yml
I wanted to keep these in place because in 2 years or less we'll be upgrading to 24.04, and they should work with minimal changes.

2024-02-21 08:58 UTC, markgoddard commented on releasenotes/notes/add-automated-ubuntu-migration-support-2d7e8a6e1a2103cc.yaml
I'll remove this.

2024-02-21 09:02 UTC, Alex-Welsh approved these changes

2024-02-21 09:06 UTC, merged