Support allowed vulnerabilities in trivy per image
stackhpc/stackhpc-kayobe-config pull request #989
Opened 2024-03-14 12:36 UTC by assumptionsandg

2024-03-22 09:14 UTC, markgoddard requested changes

2024-03-22 09:14 UTC, markgoddard commented on etc/kayobe/trivy.yml
> +  CVE-2023-31047
Do we actually want to allow this one or was it just used for testing?

2024-03-22 09:14 UTC, markgoddard commented on tools/scan-images.sh
> +  for vulnerability in $(yq -e .$imagename'_allowed_vulnerabilities' $KAYOBE_CONFIG_PATH/trivy.yml); do
Does this do the right thing if an image does not have a list defined?

Does it work if the image name has dashes in? e.g. nova-compute

2024-03-22 09:14 UTC, markgoddard commented on etc/kayobe/trivy.yml
> +  CVE-2023-31047
Should this be a list? (add `- `)

2024-03-22 09:14 UTC, markgoddard commented on etc/kayobe/trivy.yml
Unsure about the location of this file. I'd be tempted to move it somewhere else to avoid confusing operators, since it's not used by Kayobe.

Could be in the repo root, or etc/kayobe/trivy/allowed-vulnerabilities.yml

2024-06-10 14:50 UTC, holliefae commented on tools/scan-images.sh
> +  for vulnerability in $(yq -e .$imagename'_allowed_vulnerabilities' $KAYOBE_CONFIG_PATH/trivy.yml); do
Doesn't seem to error on images not being defined.

Currently using underscores for consistency in the whitelists file, but can revert if necessary.

2024-06-21 14:05 UTC, Alex-Welsh submitted a review, later dismissed

2024-06-27 10:57 UTC, markgoddard commented on etc/kayobe/trivy/allowed-vulnerabilities.yml
> +  - CVE-2024-36039
Do we need this one now that the requirements change has merged?

2024-06-27 12:49 UTC, assumptionsandg commented on etc/kayobe/trivy/allowed-vulnerabilities.yml
> +  - CVE-2024-36039
Moved to the example file setup, so people know `global_allowed_vulnerabilities` variable can be used in the future.

2024-06-27 14:02 UTC, markgoddard approved these changes

2024-06-27 14:02 UTC, merged